server:
  port: 9007
  servlet:
    #  全局路径配置
    context-path: /baseServer

spring:
  application:
    name: baseServer
  profiles:
    active: tx


logging:
  path: logs/
  level:
    org.springframework.web: debug
    com.springboot.cloud: debug
    java.sql.PreparedStatement: debug


eureka:
  instance:
    prefer-ip-address: true
    hostname: baseServer
    appname: baseServer
    ip-address: 124.222.217.230
