server:
  port: 9007
  servlet:
    #  全局路径配置
    context-path: /baseServer

spring:
  application:
    name: baseServer



logging:
  path: logs/
  level:
    org.springframework.web: debug
    com.springboot.cloud: debug
    java.sql.PreparedStatement: debug


eureka:
  instance:
    prefer-ip-address: true
    hostname: baseServer
    appname: baseServer
  client:
    serviceUrl:
      defaultZone: http://47.105.148.90:8001/eureka/